/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import AITBank.*;


/**
 *
 * @author Cliverson
 */
public class BalanceScreen extends javax.swing.JFrame
{
    Session ss;
    /**
     * Creates new form GUI
     * @param ss
     */
    public BalanceScreen(Session ss)
    {
        initComponents();
        this.ss = ss;
        if(ss.account.equals("Savings"))
        {            
            customerLabel.setText(ss.sva.getCUSTOMER_NAME());
            accountLabel.setText("Account:  " + ss.sva.getACCOUNT_NUMBER());
            balanceAmoutLabel.setText(ATM.decimalNumber.format(ss.sva.getAccountBalance()));
            daylyAmountLabel.setText(ATM.decimalNumber.format(ss.sva.getDailyWithdrawLimit()));
            avaliableAmountLabel.setText(ATM.decimalNumber.format(ss.sva.getAvaliableLimitToday()));
        }
        
        if(ss.account.equals("NetSaver"))
        {            
            customerLabel.setText(ss.nsa.getCUSTOMER_NAME());
            accountLabel.setText("Account:  " + ss.nsa.getACCOUNT_NUMBER());
            balanceAmoutLabel.setText(ATM.decimalNumber.format(ss.nsa.getAccountBalance()));
            daylyAmountLabel.setText(ATM.decimalNumber.format(ss.nsa.getDAILY_WITHDRAW_LIMIT()));
            avaliableAmountLabel.setText(ATM.decimalNumber.format(ss.nsa.getAvaliableLimitToday()));
        }
        
        if(ss.account.equals("Cheque"))
        {            
            customerLabel.setText(ss.cqa.getCUSTOMER_NAME());
            accountLabel.setText("Account:  " + ss.cqa.getACCOUNT_NUMBER());
            balanceAmoutLabel.setText(ATM.decimalNumber.format(ss.cqa.getAccountBalance()));
            daylyWithdrawLabel.setText("");
            withdrawAvaliableLabel.setText("");
        }
        
        if(ss.account.equals("Fixed"))
        {            
            customerLabel.setText(ss.fxa.getCUSTOMER_NAME());
            accountLabel.setText("Account:  " + ss.fxa.getACCOUNT_NUMBER());
            balanceAmoutLabel.setText(ATM.decimalNumber.format(ss.fxa.getAccountBalance()));
            daylyWithdrawLabel.setText("Begin of Contract:");
            daylyAmountLabel.setText(ss.fxa.getContractStartDate());
            withdrawAvaliableLabel.setText("End of Contract");
            avaliableAmountLabel.setText(ss.fxa.getContractEndDate());
            earlyWithdrawLabel.setText("Early withdraw:");
            earlyWithdrawValueLabel.setText(ss.fxa.getEarlyWithdraw());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        aitLogoLabel = new javax.swing.JLabel();
        middleLeftButton = new javax.swing.JButton();
        upperRightButton = new javax.swing.JButton();
        upperLeftButton = new javax.swing.JButton();
        middleRightButton = new javax.swing.JButton();
        bottomRightButton = new javax.swing.JButton();
        bottomRightLabel = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        daylyWithdrawLabel = new javax.swing.JLabel();
        withdrawAvaliableLabel = new javax.swing.JLabel();
        balanceAmoutLabel = new javax.swing.JLabel();
        daylyAmountLabel = new javax.swing.JLabel();
        avaliableAmountLabel = new javax.swing.JLabel();
        earlyWithdrawLabel = new javax.swing.JLabel();
        earlyWithdrawValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AIT Bank");
        setName("bankFrame"); // NOI18N

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setPreferredSize(new java.awt.Dimension(761, 504));

        aitLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/AITBankLogo.jpg"))); // NOI18N

        middleLeftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/button_selectLeft.png"))); // NOI18N
        middleLeftButton.setBorder(null);
        middleLeftButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/button_selectLeft_click.png"))); // NOI18N
        middleLeftButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                middleLeftButtonActionPerformed(evt);
            }
        });

        upperRightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/button_selectRight.png"))); // NOI18N
        upperRightButton.setBorder(null);
        upperRightButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/button_selectRight_click.png"))); // NOI18N
        upperRightButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                upperRightButtonActionPerformed(evt);
            }
        });

        upperLeftButton.setBackground(new java.awt.Color(0, 174, 179));
        upperLeftButton.setForeground(new java.awt.Color(0, 0, 0));
        upperLeftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/button_selectLeft.png"))); // NOI18N
        upperLeftButton.setBorder(null);
        upperLeftButton.setBorderPainted(false);
        upperLeftButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/button_selectLeft_click.png"))); // NOI18N
        upperLeftButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                upperLeftButtonActionPerformed(evt);
            }
        });

        middleRightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/button_selectRight.png"))); // NOI18N
        middleRightButton.setBorder(null);
        middleRightButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/button_selectRight_click.png"))); // NOI18N
        middleRightButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                middleRightButtonActionPerformed(evt);
            }
        });

        bottomRightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/button_selectRight.png"))); // NOI18N
        bottomRightButton.setBorder(null);
        bottomRightButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/AITBank/Images/button_selectRight_click.png"))); // NOI18N
        bottomRightButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bottomRightButtonActionPerformed(evt);
            }
        });

        bottomRightLabel.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        bottomRightLabel.setForeground(new java.awt.Color(204, 204, 204));
        bottomRightLabel.setText("BACK");

        customerLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(204, 204, 204));
        customerLabel.setText("CUSTOMER NAME");

        accountLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        accountLabel.setForeground(new java.awt.Color(204, 204, 204));
        accountLabel.setText("Account: ");

        balanceLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(204, 204, 204));
        balanceLabel.setText("Balance:");

        daylyWithdrawLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        daylyWithdrawLabel.setForeground(new java.awt.Color(204, 204, 204));
        daylyWithdrawLabel.setText("Daily withdraw:");

        withdrawAvaliableLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        withdrawAvaliableLabel.setForeground(new java.awt.Color(204, 204, 204));
        withdrawAvaliableLabel.setText("Withdraw avaliable:");
        withdrawAvaliableLabel.setToolTipText("");

        balanceAmoutLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        balanceAmoutLabel.setForeground(new java.awt.Color(0, 153, 0));

        daylyAmountLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        daylyAmountLabel.setForeground(new java.awt.Color(204, 204, 204));

        avaliableAmountLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avaliableAmountLabel.setForeground(new java.awt.Color(204, 204, 204));

        earlyWithdrawLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        earlyWithdrawLabel.setForeground(new java.awt.Color(204, 204, 204));

        earlyWithdrawValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        earlyWithdrawValueLabel.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upperLeftButton)
                    .addComponent(middleLeftButton))
                .addGap(211, 211, 211)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerLabel)
                            .addComponent(accountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(upperRightButton))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(withdrawAvaliableLabel)
                            .addComponent(daylyWithdrawLabel)
                            .addComponent(earlyWithdrawLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(daylyAmountLabel)
                                    .addComponent(avaliableAmountLabel))
                                .addGap(162, 162, 162)
                                .addComponent(middleRightButton))
                            .addComponent(earlyWithdrawValueLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bottomRightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bottomRightButton))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(balanceLabel)
                        .addGap(112, 112, 112)
                        .addComponent(balanceAmoutLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(aitLogoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(aitLogoLabel)
                .addGap(40, 40, 40)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(upperLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(middleLeftButton)
                        .addGap(118, 118, 118)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bottomRightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottomRightButton))
                        .addGap(12, 12, 12))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(customerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accountLabel)
                                .addGap(31, 31, 31)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(balanceLabel)
                                    .addComponent(balanceAmoutLabel)))
                            .addComponent(upperRightButton))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(daylyWithdrawLabel)
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(withdrawAvaliableLabel)
                                    .addComponent(avaliableAmountLabel)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(middleRightButton))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(daylyAmountLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(earlyWithdrawValueLabel)
                            .addComponent(earlyWithdrawLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        aitLogoLabel.getAccessibleContext().setAccessibleName("AITLogoLabel");
        aitLogoLabel.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottomRightButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bottomRightButtonActionPerformed
    {//GEN-HEADEREND:event_bottomRightButtonActionPerformed
        ATM.setMessage("");
        ss.account = "";
        ss.function = "";
        ss.value = 0;
        FunctionsScreen fns = new FunctionsScreen(ss);
        fns.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bottomRightButtonActionPerformed

    private void middleRightButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_middleRightButtonActionPerformed
    {//GEN-HEADEREND:event_middleRightButtonActionPerformed

    }//GEN-LAST:event_middleRightButtonActionPerformed

    private void upperLeftButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_upperLeftButtonActionPerformed
    {//GEN-HEADEREND:event_upperLeftButtonActionPerformed

    }//GEN-LAST:event_upperLeftButtonActionPerformed

    private void upperRightButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_upperRightButtonActionPerformed
    {//GEN-HEADEREND:event_upperRightButtonActionPerformed

    }//GEN-LAST:event_upperRightButtonActionPerformed

    private void middleLeftButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_middleLeftButtonActionPerformed
    {//GEN-HEADEREND:event_middleLeftButtonActionPerformed

    }//GEN-LAST:event_middleLeftButtonActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Nimbus".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        }
//        catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(AccountsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(AccountsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(AccountsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            java.util.logging.Logger.getLogger(AccountsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                new AccountsScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JLabel aitLogoLabel;
    private javax.swing.JLabel avaliableAmountLabel;
    private javax.swing.JLabel balanceAmoutLabel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton bottomRightButton;
    private javax.swing.JLabel bottomRightLabel;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel daylyAmountLabel;
    private javax.swing.JLabel daylyWithdrawLabel;
    private javax.swing.JLabel earlyWithdrawLabel;
    private javax.swing.JLabel earlyWithdrawValueLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton middleLeftButton;
    private javax.swing.JButton middleRightButton;
    private javax.swing.JButton upperLeftButton;
    private javax.swing.JButton upperRightButton;
    private javax.swing.JLabel withdrawAvaliableLabel;
    // End of variables declaration//GEN-END:variables
}
